### PR TITLE
Commit & Push updated

### LINKED ISSUE #1529: [IDE] Git - Unstaged files are tracked per push attempt, not per successful push
**Describe the bug**
Working on a private git repo may result in changes being lost in cases of unsuccessful push.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a private repo and clone it.
2. Add several files with some code in each one.
3. Go to the Git perspective, fill-in necessary data, Commit & Push.
4. Go to Workspace.
5. Update content of any of the files.
6. Go to the Git perspective, select the project, click Refresh icon in Staging tab if necessary, move updated file to Staged files list.
7. Intentionally provide wrong username or password/Github token, i.e. simulate a typo and click Commit & Push.
8. You will see an error message but the updated file will disappear from Staged files list as if it was successfully pushed.
9. Go back to Workspace and update the content of another file.
10. Open the Git perspective again. In the Unstaged files list you will see the file updated in p.9 but not the file updated in p. 5 (which is not updated in Git).
11. Provide correct username and password/Github token, fill-in the other fields, move the file to Staged list and click on Commit & Push.
12. Check in Git that the second file's content (the one from p.9) is updated but the first file's content (the one from p. 5) is not. 

**Expected behaviour**
If push fails unstaged files must remain unstaged and the customer must be given the opportunity to push them later.

**Desktop (please complete the following information):**
 - iOS
 - Google Chrome
 - Version 97.0.4692.99 (Official Build) (arm64)

### PR DESCRIPTION
**Pull request by dimitarquanterall**
Fixes [#1529](https://github.com/eclipse/dirigible/issues/1529)

### CODE REVIEW

**Review by ThuF — APPROVED** [review]
+1 seems good to me, @StanZGenchev do you have any comments, or we could safely merge this PR?

**Comment by StanZGenchev** [comment]
Why is there `setTimeout` on line 376? Using `setTimeout` is not a good idea in general.

**Comment by StanZGenchev** [comment]
Resolved.

**Review by StanZGenchev — APPROVED** [review]

**Comment by ThuF** [comment]
@dimitarquanterall PR in https://github.com/eclipse/dirigible should be made with the respective changes:
- Clone Eclipse Dirigible
- Navigate to [ide/ui/ide-git](https://github.com/eclipse/dirigible/tree/master/ide/ui/ide-git) folder
- Execute `mvn clean install -P content`
- Execute `mvn clean install`
- Create new PR in Eclipse Dirigible

**Pull request merged**
